// @/constants/skills/guardian-knight

export const GUARDIAN_KNIGHT_SKILL_ID = {
  CLEAVE :              'GUARDIAN_KNIGHT_SKILL00',
  RENDING_FINISHER :    'GUARDIAN_KNIGHT_SKILL16',
  EXPLOSION_FINISHER :  'GUARDIAN_KNIGHT_SKILL17',
  DEEP_IMPACT :         'GUARDIAN_KNIGHT_SKILL19',
  GUARDIAN_BACKRASH:    'GUARDIAN_KNIGHT_SKILL20',
  BREATH_OF_EMBERES:    'GUARDIAN_KNIGHT_SKILL21'
} as const;

export const GUARDIAN_KNIGHT_SKILL_NAME = {
  [GUARDIAN_KNIGHT_SKILL_ID.CLEAVE]:              '클리브',
  [GUARDIAN_KNIGHT_SKILL_ID.RENDING_FINISHER]:    '렌딩 피니셔',
  [GUARDIAN_KNIGHT_SKILL_ID.EXPLOSION_FINISHER]:  '익스플로전 피니셔',
  [GUARDIAN_KNIGHT_SKILL_ID.DEEP_IMPACT]:         '딥 임팩트',
  [GUARDIAN_KNIGHT_SKILL_ID.GUARDIAN_BACKRASH]:   '가디언 백래시',
  [GUARDIAN_KNIGHT_SKILL_ID.BREATH_OF_EMBERES]:   '브레스 오브 엠버레스'
} as const;

/**
 * [트라이포드 ID 선언]
 * 규칙: 스킬ID_티어인덱스
 */
export const GUARDIAN_KNIGHT_TRIPOD_ID = {
  /* 클리브 (CLEAVE) */
  CLEAVE_A1: `${GUARDIAN_KNIGHT_SKILL_ID.CLEAVE}_A1`,
  CLEAVE_A2: `${GUARDIAN_KNIGHT_SKILL_ID.CLEAVE}_A2`,
  CLEAVE_A3: `${GUARDIAN_KNIGHT_SKILL_ID.CLEAVE}_A3`,
  CLEAVE_B1: `${GUARDIAN_KNIGHT_SKILL_ID.CLEAVE}_B1`,
  CLEAVE_B2: `${GUARDIAN_KNIGHT_SKILL_ID.CLEAVE}_B2`,
  CLEAVE_B3: `${GUARDIAN_KNIGHT_SKILL_ID.CLEAVE}_B3`,
  CLEAVE_C1: `${GUARDIAN_KNIGHT_SKILL_ID.CLEAVE}_C1`,
  CLEAVE_C2: `${GUARDIAN_KNIGHT_SKILL_ID.CLEAVE}_C2`,

  /* 렌딩 피니셔 (RENDING_FINISHER) */
  RENDING_FINISHER_A1: `${GUARDIAN_KNIGHT_SKILL_ID.RENDING_FINISHER}_A1`,
  RENDING_FINISHER_A2: `${GUARDIAN_KNIGHT_SKILL_ID.RENDING_FINISHER}_A2`,
  RENDING_FINISHER_A3: `${GUARDIAN_KNIGHT_SKILL_ID.RENDING_FINISHER}_A3`,
  RENDING_FINISHER_B1: `${GUARDIAN_KNIGHT_SKILL_ID.RENDING_FINISHER}_B1`,
  RENDING_FINISHER_B2: `${GUARDIAN_KNIGHT_SKILL_ID.RENDING_FINISHER}_B2`,
  RENDING_FINISHER_C1: `${GUARDIAN_KNIGHT_SKILL_ID.RENDING_FINISHER}_C1`,
  RENDING_FINISHER_C2: `${GUARDIAN_KNIGHT_SKILL_ID.RENDING_FINISHER}_C2`,

  /* 익스플로전 피니셔 (EXPLOSION_FINISHER) */
  EXPLOSION_FINISHER_A1: `${GUARDIAN_KNIGHT_SKILL_ID.EXPLOSION_FINISHER}_A1`,
  EXPLOSION_FINISHER_A2: `${GUARDIAN_KNIGHT_SKILL_ID.EXPLOSION_FINISHER}_A2`,
  EXPLOSION_FINISHER_A3: `${GUARDIAN_KNIGHT_SKILL_ID.EXPLOSION_FINISHER}_A3`,
  EXPLOSION_FINISHER_B1: `${GUARDIAN_KNIGHT_SKILL_ID.EXPLOSION_FINISHER}_B1`,
  EXPLOSION_FINISHER_B2: `${GUARDIAN_KNIGHT_SKILL_ID.EXPLOSION_FINISHER}_B2`,
  EXPLOSION_FINISHER_C1: `${GUARDIAN_KNIGHT_SKILL_ID.EXPLOSION_FINISHER}_C1`,
  EXPLOSION_FINISHER_C2: `${GUARDIAN_KNIGHT_SKILL_ID.EXPLOSION_FINISHER}_C2`,
} as const;

export const GUARDIAN_KNIGHT_TRIPOD_NAME = {
  /* 클리브 */
  [GUARDIAN_KNIGHT_TRIPOD_ID.CLEAVE_A1]: '피해증폭',
  [GUARDIAN_KNIGHT_TRIPOD_ID.CLEAVE_A2]: '돌진',
  [GUARDIAN_KNIGHT_TRIPOD_ID.CLEAVE_A3]: '재빠른 손놀림',
  [GUARDIAN_KNIGHT_TRIPOD_ID.CLEAVE_B1]: '증강',
  [GUARDIAN_KNIGHT_TRIPOD_ID.CLEAVE_B2]: '약육강식',
  [GUARDIAN_KNIGHT_TRIPOD_ID.CLEAVE_B3]: '약점 포착',
  [GUARDIAN_KNIGHT_TRIPOD_ID.CLEAVE_C1]: '화염 폭풍',
  [GUARDIAN_KNIGHT_TRIPOD_ID.CLEAVE_C2]: '휩쓸기',

  /* 렌딩 피니셔 */
  [GUARDIAN_KNIGHT_TRIPOD_ID.RENDING_FINISHER_A1]: '재빠른 손놀림',
  [GUARDIAN_KNIGHT_TRIPOD_ID.RENDING_FINISHER_A2]: '단단한 비늘',
  [GUARDIAN_KNIGHT_TRIPOD_ID.RENDING_FINISHER_A3]: '정면 승부',
  [GUARDIAN_KNIGHT_TRIPOD_ID.RENDING_FINISHER_B1]: '응축된 힘',
  [GUARDIAN_KNIGHT_TRIPOD_ID.RENDING_FINISHER_B2]: '약점 포착',
  [GUARDIAN_KNIGHT_TRIPOD_ID.RENDING_FINISHER_C1]: '깨어난 본능',
  [GUARDIAN_KNIGHT_TRIPOD_ID.RENDING_FINISHER_C2]: '공간절삭',

  /* 익스플로전 피니셔 */
  [GUARDIAN_KNIGHT_TRIPOD_ID.EXPLOSION_FINISHER_A1]: '재빠른 손놀림',
  [GUARDIAN_KNIGHT_TRIPOD_ID.EXPLOSION_FINISHER_A2]: '단단한 비늘',
  [GUARDIAN_KNIGHT_TRIPOD_ID.EXPLOSION_FINISHER_A3]: '뇌진탕',
  [GUARDIAN_KNIGHT_TRIPOD_ID.EXPLOSION_FINISHER_B1]: '응축된 힘',
  [GUARDIAN_KNIGHT_TRIPOD_ID.EXPLOSION_FINISHER_B2]: '약점 포착',
  [GUARDIAN_KNIGHT_TRIPOD_ID.EXPLOSION_FINISHER_C1]: '붉은 심장',
  [GUARDIAN_KNIGHT_TRIPOD_ID.EXPLOSION_FINISHER_C2]: '푸른 심장',
} as const;